secrets-encryption: "true"
protect-kernel-defaults: "true"
kube-apiserver-arg:
- "enable-admission-plugins=NodeRestriction,PodSecurityPolicy,NamespaceLifecycle,ServiceAccount"
- "audit-log-path=/var/lib/rancher/k3s/server/logs/audit.log"
- "audit-policy-file=/var/lib/rancher/k3s/server/audit.yaml"
- "audit-log-maxage=30"
- "audit-log-maxbackup=10"
- "audit-log-maxsize=100"
- "request-timeout=300s"
- "service-account-lookup=true"
kube-controller-manager-arg:
- "terminated-pod-gc-threshold=10"
- "use-service-account-credentials=true"
kubelet-arg:
- "make-iptables-util-chains=true"
- "streaming-connection-idle-timeout=5m"
