# # see: https://terraform-docs.io/user-guide/configuration/version
# version: ">= 0.10, < 0.12"

# see: https://terraform-docs.io/user-guide/configuration/formatter
formatter: markdown table

header-from: docs/header.md

content: |-
  {{ .Header }}

  ## [Example](docs/example.tf)

  ```hcl
  {{ include "docs/example.tf" }}
  ```

  {{ .Requirements }}

  {{ .Inputs }}

  {{ .Outputs }}

# see: https://terraform-docs.io/user-guide/configuration/sort
sort:
  enabled: true
  by: name

# see: https://terraform-docs.io/user-guide/configuration/settings
settings:
  indent: 4
  escape: false
  default: false
  required: false
  type: true
